# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true as per feb09/2016 email from github

# Setup
title:               Mississauga Coding
tagline:             'A meetup group'
description:         'The official website for the meetup group Mississauga Coding.'
url:                 http://www.meetup.com/Mississauga-Coding-learn-to-code/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              The Organizers
  url:               http://www.meetup.com/Mississauga-Coding-learn-to-code/members/?op=leaders
  email:             Mississaugacoding@gmail.com


github:
  url:				https://github.com/MississaugaCoding


# Custom vars
version:             1.0.0
